source 'https://rubygems.org'
gem 'redcarpet'
gem 'sanitize'
gem 'jekyll'
gem "couchbase-theme", path: "./../../docs-style-guide/jekyll-theme"

group :jekyll_plugins do
    gem 'jekyll-livereload'
end